### ISSUE TITLE
Error when installing requirements

### ISSUE THREAD

**Issue by nightmare199x** [anbusystem/autoairdrop#2]
Hi, i met these error when installing requirements, please help.

Building wheels for collected packages: ed25519
  Building wheel for ed25519 (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building wheel for ed25519 (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [3 lines of output]
      UPDATING build\lib.win-amd64-cpython-311\ed25519/_version.py
      set build\lib.win-amd64-cpython-311\ed25519/_version.py to '1.5'
      error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for ed25519
Failed to build ed25519
ERROR: Could not build wheels for ed25519, which is required to install pyproject.toml-based projects

**Comment by silverwolfceh** [comment]
Download build tool, install and try again: https://visualstudio.microsoft.com/visual-cpp-build-tools/
