### ISSUE TITLE
Asking a question 

### ISSUE THREAD

**Issue by iPurya** [anbusystem/autoairdrop#3]
Hi dear,
can i ask you how did you mitm telegram webapp ?
how can i intercept telegram webapps requests using burpsuite for example ?

**Comment by silverwolfceh** [comment]
No bro,

We dont intercept the telegram web app, we forced the app to display on web browser with some JavaScript. Then we just observe the network console on browser' dev tool

**Comment by silverwolfceh** [comment]
There is a telegram support channel for this repo: https://t.me/teleairdropscript

If you have any concerns or questions, go there and ask.
